artifacts_root: artifacts

data_ingestion:
      root_dir: artifacts/data_ingestion
      source_url: https://www.kaggle.com/competitions/playground-series-s4e12/data
      local_data_file: artifacts/data_ingestion/playground-series-s4e12.zip
      unzip_dir: artifacts/data_ingestion
      comp_name: 'playground-series-s4e12'

